{
  "swagger": "2.0",
  "info": {
    "description": "This is the API",
    "title": "My API",
    "version": "1.0.0"
  },
  "basePath": "/",
  "paths": {
    "/api/content": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "ids": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "ids"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or more content/repo",
        "operationId": "DeleteContent"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All content",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "createdOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "domain": {
                        "enum": [
                          "scripture",
                          "gloss",
                          "parascriptural",
                          "peripheral"
                        ],
                        "type": "string",
                        "x-nullable": true
                      },
                      "id": {
                        "maxLength": 256,
                        "type": "string"
                      },
                      "languageId": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "level": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "modifiedOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "name": {
                        "maxLength": 256,
                        "type": "string"
                      },
                      "namespace": {
                        "maxLength": 256,
                        "type": "string"
                      },
                      "resourceType": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "type": {
                        "enum": [
                          "text",
                          "audio",
                          "video",
                          "braille"
                        ],
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "languageId",
                      "name",
                      "namespace",
                      "type",
                      "domain",
                      "resourceType",
                      "createdOn",
                      "modifiedOn",
                      "level"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                },
                "ok": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "ok",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get content",
        "operationId": "GetContent"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of projects/content",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/content"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object with inserted content data",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more repo/content",
        "operationId": "CreateContent"
      }
    },
    "/api/country": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "alpha2Codes": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "alpha2Codes"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or more countries",
        "operationId": "DeleteCountry"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All countries",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "alpha2": {
                        "type": "string"
                      },
                      "alpha3": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "createdOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "id": {
                        "type": "number"
                      },
                      "modifiedOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "name": {
                        "type": "string"
                      },
                      "population": {
                        "type": "number",
                        "x-nullable": true
                      },
                      "worldRegionId": {
                        "type": "number"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "worldRegionId",
                      "createdOn",
                      "modifiedOn",
                      "alpha2",
                      "alpha3",
                      "population"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                }
              },
              "required": [
                "message",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get country",
        "operationId": "GetCountry"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of countries",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/country"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object with inserted country data",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more country",
        "operationId": "CreateCountry"
      }
    },
    "/api/git": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of username and repo (composite key) used to delete git repos",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "userRepo": {
                  "items": {
                    "properties": {
                      "repo": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "username",
                      "repo"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                }
              },
              "required": [
                "userRepo"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or git entries",
        "operationId": "DeleteGit"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All git entries",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "contentId": {
                        "type": "string"
                      },
                      "id": {
                        "type": "number"
                      },
                      "repoName": {
                        "type": "string"
                      },
                      "repoUrl": {
                        "type": "string"
                      },
                      "username": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "contentId",
                      "username",
                      "repoName",
                      "repoUrl"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                },
                "ok": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "ok",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get git entries",
        "operationId": "GetGit"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of git entries to add",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/git"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Confirmation of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more git entries",
        "operationId": "CreateGit"
      }
    },
    "/api/language": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of ietfCodes corresponding to languages to delete",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "ietfCodes": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "ietfCodes"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or more languages",
        "operationId": "DeleteLanguage"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All languages",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "createdOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "direction": {
                        "enum": [
                          "ltr",
                          "rtl"
                        ],
                        "type": "string"
                      },
                      "englishName": {
                        "type": "string"
                      },
                      "homeCountryAlpha2": {
                        "type": "string"
                      },
                      "id": {
                        "type": "string"
                      },
                      "ietfCode": {
                        "type": "string"
                      },
                      "isOralLanguage": {
                        "type": "boolean",
                        "x-nullable": true
                      },
                      "iso6393": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "modifiedOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "nationalName": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "ietfCode",
                      "nationalName",
                      "englishName",
                      "direction",
                      "iso6393",
                      "createdOn",
                      "modifiedOn",
                      "isOralLanguage",
                      "homeCountryAlpha2"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                },
                "ok": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "ok",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get language",
        "operationId": "GetLanguage"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of languages",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/language"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object with inserted language data",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more language",
        "operationId": "CreateLanguage"
      }
    },
    "/api/region": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of regions by their regionName corresponding to regions to delete",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "regionNames": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "regionNames"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or more regions",
        "operationId": "DeleteRegion"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All regions",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "createdOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "id": {
                        "type": "number"
                      },
                      "modifiedOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "name": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "name",
                      "createdOn",
                      "modifiedOn"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                },
                "ok": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "ok",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get region",
        "operationId": "GetRegion"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of regions",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/region"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Object with inserted region data",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more regions",
        "operationId": "CreateRegion"
      }
    },
    "/api/rendering": {
      "delete": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of namespaces and content ids (e.g. namespace=wacs, contentId=user-repo to use to delete renderings",
            "in": "body",
            "name": "body",
            "schema": {
              "properties": {
                "contentIds": {
                  "items": {
                    "type": "string"
                  },
                  "type": "array"
                }
              },
              "required": [
                "contentIds"
              ],
              "type": "object"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "confirmation message of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Delete one or more renderings",
        "operationId": "DeleteRendering"
      },
      "get": {
        "produces": [
          "application/json"
        ],
        "parameters": [],
        "responses": {
          "200": {
            "description": "All renderings",
            "schema": {
              "properties": {
                "data": {
                  "items": {
                    "properties": {
                      "contentId": {
                        "type": "string"
                      },
                      "createdAt": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "fileSizeBytes": {
                        "type": "number",
                        "x-nullable": true
                      },
                      "fileType": {
                        "type": "string"
                      },
                      "hash": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "id": {
                        "type": "number"
                      },
                      "modifiedOn": {
                        "type": "string",
                        "x-nullable": true
                      },
                      "url": {
                        "type": "string"
                      }
                    },
                    "required": [
                      "id",
                      "contentId",
                      "fileType",
                      "fileSizeBytes",
                      "url",
                      "hash",
                      "createdAt",
                      "modifiedOn"
                    ],
                    "type": "object"
                  },
                  "type": "array"
                },
                "message": {
                  "type": "string"
                },
                "ok": {
                  "type": "boolean"
                }
              },
              "required": [
                "message",
                "ok",
                "data"
              ],
              "type": "object"
            }
          }
        },
        "description": "Get renderings",
        "operationId": "GetRendering"
      },
      "post": {
        "consumes": [
          "applications/json"
        ],
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "description": "A list of renders/links to add",
            "in": "body",
            "name": "body",
            "schema": {
              "$ref": "#/definitions/rendering"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Confirmation of successful operation",
            "schema": {
              "$ref": "#/definitions/okRes"
            }
          },
          "400": {
            "description": "Error with details of improper request",
            "schema": {
              "$ref": "#/definitions/apiError"
            }
          }
        },
        "description": "Add one or more renders/links of content",
        "operationId": "CreateRendering"
      }
    }
  },
  "definitions": {
    "apiError": {
      "properties": {
        "addlErrs": {
          "items": {
            "properties": {
              "message": {
                "type": "string"
              },
              "name": {
                "type": "string"
              }
            },
            "required": [
              "message",
              "name"
            ],
            "type": "object"
          },
          "type": "array"
        },
        "err": {
          "properties": {
            "didErr": {
              "type": "boolean"
            },
            "issues": {
              "items": {
                "x-nullable": true
              },
              "type": "array"
            },
            "name": {
              "type": "string"
            }
          },
          "type": "object"
        },
        "message": {
          "type": "string"
        }
      },
      "required": [
        "message",
        "err",
        "addlErrs"
      ],
      "type": "object"
    },
    "content": {
      "example": [
        {
          "createdOn": "2025-03-24T21:09:44.194Z",
          "domain": "peripheral",
          "gitEntry": {
            "namespace": "wacs",
            "repoName": "clipper",
            "repoUrl": "https://knotty-headquarters.net/",
            "username": "Ebba_Morissette"
          },
          "languageId": "kht",
          "level": "medium",
          "meta": {
            "showOnBiel": false,
            "status": "not approved"
          },
          "modifiedOn": "2025-03-28T14:29:04.763Z",
          "name": "ulb",
          "namespace": "wacs",
          "resourceType": "tq",
          "type": "text"
        }
      ],
      "items": {
        "properties": {
          "createdOn": {
            "type": "string",
            "x-nullable": true
          },
          "domain": {
            "enum": [
              "scripture",
              "gloss",
              "parascriptural",
              "peripheral"
            ],
            "type": "string",
            "x-nullable": true
          },
          "gitEntry": {
            "properties": {
              "id": {
                "type": "number"
              },
              "repoName": {
                "type": "string"
              },
              "repoUrl": {
                "type": "string"
              },
              "username": {
                "type": "string"
              }
            },
            "required": [
              "username",
              "repoName",
              "repoUrl"
            ],
            "type": "object"
          },
          "id": {
            "type": "string"
          },
          "languageId": {
            "type": "string",
            "x-nullable": true
          },
          "level": {
            "type": "string",
            "x-nullable": true
          },
          "meta": {
            "properties": {
              "id": {
                "type": "number"
              },
              "showOnBiel": {
                "type": "boolean"
              },
              "status": {
                "type": "string"
              }
            },
            "required": [
              "showOnBiel",
              "status"
            ],
            "type": "object"
          },
          "modifiedOn": {
            "type": "string",
            "x-nullable": true
          },
          "name": {
            "maxLength": 256,
            "type": "string"
          },
          "namespace": {
            "type": "string"
          },
          "resourceType": {
            "type": "string",
            "x-nullable": true
          },
          "type": {
            "enum": [
              "text",
              "audio",
              "video",
              "braille"
            ],
            "type": "string"
          }
        },
        "required": [
          "name",
          "namespace",
          "type"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "country": {
      "example": [
        {
          "alpha2": "BN",
          "alpha3": "CRI",
          "createdOn": "2023-12-13T01:16:56.564Z",
          "modifiedOn": "2023-08-19T09:35:29.012Z",
          "name": "Samoa",
          "population": 461394755,
          "regionName": "Austrailia"
        }
      ],
      "items": {
        "properties": {
          "alpha2": {
            "type": "string"
          },
          "alpha3": {
            "type": "string",
            "x-nullable": true
          },
          "createdOn": {
            "type": "string",
            "x-nullable": true
          },
          "id": {
            "type": "number"
          },
          "modifiedOn": {
            "type": "string",
            "x-nullable": true
          },
          "name": {
            "type": "string"
          },
          "population": {
            "type": "number",
            "x-nullable": true
          },
          "regionName": {
            "type": "string"
          }
        },
        "required": [
          "name",
          "alpha2",
          "regionName"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "git": {
      "example": [
        {
          "contentId": "wacs-user-repo",
          "repoName": "readily",
          "repoUrl": "https://gummy-waveform.biz/",
          "username": "Esta_Bayer"
        }
      ],
      "items": {
        "properties": {
          "contentId": {
            "type": "string"
          },
          "id": {
            "type": "number"
          },
          "repoName": {
            "type": "string"
          },
          "repoUrl": {
            "type": "string"
          },
          "username": {
            "type": "string"
          }
        },
        "required": [
          "contentId",
          "username",
          "repoName",
          "repoUrl"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "language": {
      "example": [
        {
          "allCountryAlpha2": [
            "SS",
            "CR"
          ],
          "alternateNames": [
            "inside",
            "consequently",
            "offbeat"
          ],
          "createdOn": "2025-03-12T15:30:57.764Z",
          "direction": "ltr",
          "englishName": "unless",
          "homeCountryAlpha2": "LA",
          "id": "fqcyKyFEoH",
          "ietfCode": "ats",
          "isOralLanguage": true,
          "iso6393": "nwhornsr",
          "nationalName": "wisdom",
          "waLangMeta": {
            "isGateway": true,
            "showOnBiel": false
          }
        }
      ],
      "items": {
        "properties": {
          "allCountryAlpha2": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "alternateNames": {
            "items": {
              "type": "string"
            },
            "type": "array"
          },
          "createdOn": {
            "type": "string",
            "x-nullable": true
          },
          "direction": {
            "enum": [
              "ltr",
              "rtl"
            ],
            "type": "string"
          },
          "englishName": {
            "type": "string"
          },
          "gatewayIetf": {
            "type": "string"
          },
          "homeCountryAlpha2": {
            "type": "string"
          },
          "id": {
            "type": "string"
          },
          "ietfCode": {
            "type": "string"
          },
          "isOralLanguage": {
            "type": "boolean",
            "x-nullable": true
          },
          "iso6393": {
            "type": "string",
            "x-nullable": true
          },
          "modifiedOn": {
            "type": "string",
            "x-nullable": true
          },
          "nationalName": {
            "type": "string"
          },
          "waLangMeta": {
            "properties": {
              "isGateway": {
                "type": "boolean"
              },
              "showOnBiel": {
                "type": "boolean"
              }
            },
            "required": [
              "isGateway",
              "showOnBiel"
            ],
            "type": "object"
          }
        },
        "required": [
          "id",
          "ietfCode",
          "nationalName",
          "englishName",
          "direction",
          "homeCountryAlpha2"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "okRes": {
      "properties": {
        "message": {
          "type": "string"
        },
        "ok": {
          "default": true,
          "type": "boolean"
        }
      },
      "required": [
        "message"
      ],
      "type": "object"
    },
    "region": {
      "example": [
        {
          "createdOn": "2023-07-27T23:47:58.068Z",
          "modifiedOn": "2025-01-20T19:09:33.551Z",
          "name": "Africa"
        }
      ],
      "items": {
        "properties": {
          "createdOn": {
            "type": "string",
            "x-nullable": true
          },
          "id": {
            "type": "number"
          },
          "modifiedOn": {
            "type": "string",
            "x-nullable": true
          },
          "name": {
            "type": "string"
          }
        },
        "required": [
          "name"
        ],
        "type": "object"
      },
      "type": "array"
    },
    "rendering": {
      "examples": [
        [
          {
            "contentId": "user-repo",
            "createdAt": "2024-01-25T13:36:54.975Z",
            "fileSizeBytes": 7289338714914816,
            "fileType": "mp3",
            "modifiedOn": "2023-08-09T17:50:58.948Z",
            "namespace": "wacs",
            "scripturalMeta": {
              "bookName": "1 Jean",
              "bookSlug": "1JN",
              "chapter": 1,
              "isWholeBook": true,
              "isWholeProject": false,
              "tempId": "yxznk9pe8qq53w5g97yiken1"
            },
            "tempId": "yxznk9pe8qq53w5g97yiken1",
            "url": "https://embarrassed-frog.info"
          }
        ],
        [
          {
            "contentId": "user-repo",
            "createdAt": "2024-12-14T00:21:21.892Z",
            "fileSizeBytes": 2049820787212288,
            "fileType": "zip",
            "modifiedOn": "2023-12-23T20:12:25.204Z",
            "namespace": "wacs",
            "nonScripturalMeta": {
              "additionalData": "A json field",
              "name": "nonScripturalName",
              "tempId": "n9bei7lcw4ey9gvcnu51rcrb"
            },
            "scripturalMeta": {
              "bookName": "1 Jean",
              "bookSlug": "1JN",
              "chapter": 4,
              "isWholeBook": false,
              "isWholeProject": false,
              "tempId": "n9bei7lcw4ey9gvcnu51rcrb"
            },
            "tempId": "n9bei7lcw4ey9gvcnu51rcrb",
            "url": "https://creative-identity.net/"
          }
        ]
      ],
      "items": {
        "properties": {
          "contentId": {
            "type": "string"
          },
          "createdAt": {
            "type": "string",
            "x-nullable": true
          },
          "fileSizeBytes": {
            "minimum": 0,
            "type": "number",
            "x-nullable": true
          },
          "fileType": {
            "type": "string"
          },
          "hash": {
            "type": "string",
            "x-nullable": true
          },
          "id": {
            "type": "number"
          },
          "modifiedOn": {
            "type": "string",
            "x-nullable": true
          },
          "namespace": {
            "type": "string"
          },
          "nonScripturalMeta": {
            "properties": {
              "additionalData": {
                "x-nullable": true
              },
              "id": {
                "type": "number"
              },
              "name": {
                "maxLength": 256,
                "type": "string",
                "x-nullable": true
              },
              "renderingId": {
                "type": "number"
              },
              "tempId": {
                "type": "string"
              }
            },
            "required": [
              "tempId"
            ],
            "type": "object"
          },
          "scripturalMeta": {
            "properties": {
              "bookName": {
                "type": "string",
                "x-nullable": true
              },
              "bookSlug": {
                "type": "string",
                "x-nullable": true
              },
              "chapter": {
                "type": "number",
                "x-nullable": true
              },
              "id": {
                "type": "number"
              },
              "isWholeBook": {
                "type": "boolean"
              },
              "isWholeProject": {
                "type": "boolean"
              },
              "renderingId": {
                "type": "number"
              },
              "sort": {
                "type": "number",
                "x-nullable": true
              },
              "tempId": {
                "type": "string"
              }
            },
            "required": [
              "isWholeBook",
              "isWholeProject",
              "tempId"
            ],
            "type": "object"
          },
          "tempId": {
            "type": "string"
          },
          "url": {
            "type": "string"
          }
        },
        "required": [
          "contentId",
          "fileType",
          "url",
          "tempId",
          "namespace"
        ],
        "type": "object"
      },
      "type": "array"
    }
  },
  "x-components": {
    "parameters": {}
  }
}